### ISSUE TITLE
Inquiry about the Publication Status of the DiffBindFR Paper

### ISSUE THREAD

**Issue by AzraelXu** [HBioquant/DiffBind#1]
23/02/2024

Dear Professor,

I am writing to express my interest in your paper "DiffBindFR: An SE(3) Equivariant Network for Flexible Protein-Ligand Docking" that I read on arXiv. I found your paper very impressive and innovative, as it proposes a novel deep learning paradigm for protein-ligand docking that is invariant to rigid and flexible transformations.

I am a researcher in the field of computational biology and I am working on a project that involves docking large libraries of ligands to various protein targets. I am very curious about how your method performs on different datasets and scenarios, and I would love to test it on my own data.

I understand that your paper has not been published in a peer-reviewed journal yet, and I respect your decision to withhold your code until then. However, I would greatly appreciate it if you could share your code with me once your paper is accepted and published. I promise to use your code only for research purposes and to cite your paper properly.

Please let me know if you are willing to share your code with me and when I can expect to receive it. You can contact me at charlesxu7@foxmail.com.

Thank you for your time and attention. I look forward to hearing from you soon.

Sincerely,

Xu

**Comment by HBioquant** [comment]
I'm sorry to reply you so late because recently I have been working hard on other projects. Thank your for your interest in our work. We are planning to open source the code in the next few days. Please stay tuned!
