### ISSUE TITLE
problems with env.yaml

### ISSUE THREAD

**Issue by CLG68** [HBioquant/DiffBind#3]
Hi,

Just to let you know, this part in env.yaml did not work for me:

  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu117
    - --find-links https://pytorch-geometric.com/whl/torch-1.13.1+cu117.html
    - scikit-learn==1.4.1
    - scipy==1.12.0
    - torch-cluster==1.6.0+pt113cu117
    - torch-scatter==2.1.0+pt113cu117
    - torch-sparse==0.6.16+pt113cu117
    - torch-spline-conv==1.2.1+pt113cu117
    - torchmetrics==0.11.0
    - torch-geometric==2.2.0
    
    I ended up manually installing them like this:
    pip install torch-scatter==2.1.0 -f https://pytorch-geometric.com/whl/torch-1.13.1+cu117.html
    
    I also got this message when trying to run:
    
    $ python DiffBindFR/app/predict.py -h
/home/christian/anaconda3/envs/diffbindfr/lib/python3.9/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
  
  I solved this by:
  
  pip install numexpr --upgrade
  it installed: numexpr 2.9.0
  
  I don't know yet if this version will have some side effects.
  
  So in theory I solved the problems... this issue can be closed.
  
  Best

**Comment by HBioquant** [comment]
Hi, Christian,

Thanks for your feedback! The bug in PyTorcho-Geometric installation was also found in my previous tests, in my case the main reason is that the environment is not configured with the correct CUDA version (DiffBindFR requires CUDA version 11.7).

For numexpr, it is actually used by pandas to speed up numpy calculations. In my code, pandas is mainly used for data storage and multi-process acceleration, so a lower version of numexpr is fine.

I will strengthen version control in the future to avoid unnecessary UserWarning.
