### ISSUE TITLE
Segmentation fault (core dumped)  

### ISSUE THREAD

**Issue by masterwhook** [HBioquant/DiffBind#6]
Hi, many thanks for the wonderful work.
When I installed from source and run DiffBindFR,  error occurs for Segmentation fault (core dumped).
I can't figure out what is the reason. Please give some suggestions. thanks in advance.

**Comment by HBioquant** [comment]
Hi, @masterwhook,

Thank you so much for your interest in our work.

The issue you're encountering, a "Segmentation fault (core dumped)" error, often results from your CUDA configuration. If you've followed the installation instructions from our repository and used our provided [env.yaml file](https://github.com/HBioquant/DiffBindFR/blob/main/env.yaml), your CUDA version should be 11.7.

To further investigate this issue, I would recommend testing in Python's interactive mode. You can sequentially import the pytorch geometric dependencies such as pytorch, torch_scatter, torch_cluster, etc., to see if they are functioning correctly. The issue might also be related to openmm.

Once you've identified which package is causing the problem, you could try reinstalling it in the correct CUDA environment. This often resolves such issues.

Please do not hesitate to reach out if you need further assistance or if you have any other questions. 

Best

**Comment by masterwhook** [comment]
many thanks. I found the reason that caused by druglib importing.

**Comment by HBioquant** [comment]
There doesn't seem to be any more problems here. I will close the issue channel. If you have other problems, please open it again.
